--execution_mode=challenge-map
--random_seed=1337
########## Object detection flags ##########
--obstacle_detection
--nosimulator_obstacle_detection
--obstacle_detection_model_paths=/home/erdos/workspace/pylot/dependencies/models/obstacle_detection/faster-rcnn/
--obstacle_detection_model_names=faster-rcnn
--path_coco_labels=/home/erdos/workspace/pylot/dependencies/models/pylot.names
--obstacle_detection_min_score_threshold=0.3
--obstacle_detection_gpu_memory_fraction=0.4
--obstacle_detection_gpu_index=0
########## Traffic light flags ##########
--traffic_light_detection
--nosimulator_traffic_light_detection
--traffic_light_det_min_score_threshold=0.4
--traffic_light_det_gpu_memory_fraction=0.4
--traffic_light_det_gpu_index=0
--traffic_light_det_model_path=/home/erdos/workspace/pylot/dependencies/models/traffic_light_detection/faster-rcnn/
######### Tracker config #########
--obstacle_tracking
--min_matching_iou=0.2
--tracker_type=sort
--obstacle_track_max_age=5
--dynamic_obstacle_distance_threshold=30
--static_obstacle_distance_threshold=70
######### Prediction config #########
--prediction
--prediction_type=linear
--prediction_num_past_steps=10
--prediction_num_future_steps=30
########## Planning flags ##########
--planning_type=hybrid_astar
--num_waypoints_ahead=30
###### Control config #####
--control=pid
--steer_gain=1.0
--min_pid_steer_waypoint_distance=5
--min_pid_speed_waypoint_distance=5
--stop_for_people=True
--stop_for_traffic_lights=True
--stop_for_vehicles=True
--stop_at_uncontrolled_junctions=True
########## Logging flags ##########
--log_file_name=pylot_server.log
--csv_log_file_name=pylot_server.csv
--profile_file_name=pylot_server.json
--v=1
--camera_image_width=1920
--camera_image_height=1080
